opencv/cppbuild.sh, opencv/opencv-3.0.0-windows-issue56a.patch, opencv/pom.xml, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_calib3d.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_core.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_features2d.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_flann.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_highgui.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_imgcodecs.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_imgproc.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_ml.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_objdetect.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_photo.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_shape.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_stitching.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_superres.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_video.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_videoio.java, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_videostab.java
OpenCV is build from source on Windows. Patches are applied to correct issues in OpenCV.
Requires installation of Visual Studio 2013 and Windows version of CMake. The Visual Studio 2013 Community edition works fine too.
=> Fix creation of OpenCV 3 wrapper on Windows (issue #56).

caffe/cppbuild.sh
First draft of how we could get Caffe to run on every Linux distrib. cppbuild.sh now compiles all dependencies from source, and keeps the libs in cppbuild/lib for inclusion in the jar file. I only worked on x86-64.
If we run this on CentOS 6, which has the oldest glibc (2.12), it should run anywhere. There is only one additional dependency, but it is only needed at compile time for OpenBLAS:
sudo yum install gcc-gfortran
An easy way to try on a brand new CentOS is with docker:
docker run -it centos:6 bash
A strange thing is that one of the libraries seems to #define FLOAT, which breaks the compilation of the OpenCV headers in Caffe, so it is necessary to modify caffe/examples/cpp_classification/classification.cpp to add #undef FLOAT before the opencv headers (line 2).
=> Build Caffe on CentOS 6 with dependencies included

caffe/cppbuild.sh
The link for downloading hdf5 was no longer valid.
=> Correct hdf5 download link.

ffmpeg/cppbuild.sh
openssl 1.0.2d isn't available for download as far as I can see.
=> Incremented openssl dependency version for ffmpeg (second attempt)

ffmpeg/cppbuild.sh
openssl-1.0.2e returns 404 when downloaded causing compile to fail.
=> Update version of openssl

llvm/cppbuild.sh
The shell script llvm/cppbuild.sh does not run on OS X 10.11.x as it no longer ships with the 'xz' binary. This PR shifts all the handling to 'tar' -- all modern implementations will support the 'z' switch and 'xz' compression.
=> remove dep on xz

pom.xml
As agreed [here ](https://github.com/bytedeco/javacpp-presets/issues/191) maven clean phase should trigger cppbuild.sh clean
=> Hook maven clean phase with javacpp.sh clean

opencv/cppbuild.sh
The build process of OpenCV created too many modules. These interfere in other builds (like mxnet).
=> Removing unnecessary OpenCV modules

tensorflow/src/main/java/org/bytedeco/javacpp/presets/tensorflow.java
This is a first attempt at getting more familiar with javacpp and the tensorflow bindings. Not sure if is the best way to map this simple func + struct, but it compiles and works .
=> tensorflow: bind DotGraph

caffe/src/main/java/org/bytedeco/javacpp/presets/caffe.java, chilitags/cppbuild.sh, cuda/cppbuild.sh, cuda/src/main/java/org/bytedeco/javacpp/presets/cuda.java, ffmpeg/cppbuild.sh, fftw/cppbuild.sh, gsl/cppbuild.sh, leptonica/cppbuild.sh, llvm/cppbuild.sh, llvm/src/main/java/org/bytedeco/javacpp/presets/LLVM.java, mxnet/src/main/java/org/bytedeco/javacpp/presets/mxnet.java, openblas/cppbuild.sh, tensorflow/src/main/java/org/bytedeco/javacpp/presets/tensorflow.java, tesseract/cppbuild.sh
Hopefully these fix the lot for arm-hf, seems to build OK with:
mvn install -Djavacpp.platform=linux-armhf -Dplatform=linux-armhf -Dplatform.compiler=arm-linux-gnueabihf-g++ -Djavacpp.platform.compiler=arm-linux-gnueabihf-g++
to build all the presets. Only bit to check, I modified cuda and took out the linux-arm - I'm not sure that would be used? Otherwise needs some way to not try and build it for linux-armhf?
=> linux-armhf additions

ffmpeg/cppbuild.sh, pom.xml
This seems to get things working with openjdk 9 (some reported issues on earlier maven plugins), and was just ffmpeg that needed a small rework of cppbuild.sh to run natively on arm or in a cross compile setup. Natively on the pi needs platform linux-armhf specified, and openblas is really hard on the memory, seems a better chance if doc building is skipped with -Dmaven.javadoc.skip=true
=> update maven plugins for openjdk9 + arm support for native or crosscompile

opencv/cppbuild.sh, opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_text.java
Changed the opencv build script to include the text module and added a new opencv_text preset.
Tested (only) on linux-x86_64 (Ubuntu Trusty).
=> Adding support for opencv text module

README.md, llvm/README.md, llvm/cppbuild.sh, llvm/platform/pom.xml, llvm/pom.xml, platform/pom.xml
This is incomplete because I am getting errors while building it.
```
llvm-3.9.1.src/test/CodeGen/Mips/msa/elm_shift_slide.ll
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBui …
```
=> [WIP] Update LLVM to 3.9.1

caffe/src/main/java/org/bytedeco/javacpp/presets/caffe.java
Looks like data_reader.hpp is no longer in caffe, I've taken it out from the presets and compiles OK now but not sure if any other cleanup needed
=> remove old header file

pom.xml
Looks like openblas javadocs needs somewhere over 512MB mem to build, so liable to crash using default heap size on platforms with 2GB or less mem. Should fix native pi arm builds.
=> increase heap for javadocs

chilitags/cppbuild.sh, cppbuild.sh, flandmark/cppbuild.sh
Jenkins is failing to build this, wonder if something to do with new opencv version or update to flandmark maybe. 
Previously when it was building OK it looked like this
rebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
-- Check for working C compiler: /var/lib/jenkins/Android/android-ndk//toolchains/arm-linux-androideabi-4.9/p
rebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /var/lib/jenkins/Android/android-ndk//toolchains/arm-linux-androideabi-4.9
/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
-- Check for working CXX compiler: /var/lib/jenkins/Android/android-ndk//toolchains/arm-linux-androide …
=> fix issue with flandmark androidarm build

ffmpeg/cppbuild.sh
ffmpeg+x264 for windows use by default windows native threads (win32thread),
while ffmpeg+x264 in javacpp use pthread.
ffmpeg+x264 in javacpp take deadlocks in encoding
when setting tune option to zerolatency that is x264's option.
=> Deadlock on ffmpeg+x264 for windows encode with tune=zerolatency

ffmpeg/cppbuild.sh
- Added commands for download, untar and install vo-amrwbenc library
- Enabled AMR-WB encoder in FFmpeg using --enable-libvo-amrwbenc parameter
=> Enabled AMR-WB encoding support to FFmpeg

ffmpeg/cppbuild.sh
I'd like to build `nvenc`, use NVIDIA GPU for encoding or decoding as GPGPU, into ffmpeg as well, so we need `CUDA` to use `nvenc`
To get ffmpeg with `nvenc`, all we have to do is adding `--enable-nvenc` to ffmpeg configure option.
I've checked the build made success on windows-x86_64 platform.
I think this commit relates with #389 .
Thank you.
=> ffmpeg with nvenc

.travis.yml, openblas/cppbuild.sh, openblas/src/main/java/org/bytedeco/javacpp/presets/openblas.java, pom.xml
With this PR, I can build the jars required for iOS deployment:
mvn -DskipTests -Dmaven.javadoc.skip=true -Djavacpp.platform=ios-x86_64  -Djavacpp.cppbuild.skip=true  install
mvn -DskipTests -Dmaven.javadoc.skip=true -Djavacpp.platform=ios-arm64  -Djavacpp.cppbuild.skip=true  install
=> Build OpenBlas and mkl for ios (x86_64 and aarch64)

tensorflow/README.md, tensorflow/cppbuild.sh, tensorflow/pom.xml, tensorflow/src/main/java/org/bytedeco/javacpp/presets/tensorflow.java
Tested with cuda 9.0 + cudnn 7.0 and cuda 9.2 + cudnn 7.1
Is it possible to merge attributes from other platform annotation? Right now I had to copy the "link" attributes from the "windows" platform to the "windows-x86_64" with "-gpu" extension.
Furthermore it might be better to exchange the "-gpu" extension with "-cuda90" or "-cuda92". On the other hand all the different configurations are horrible (e.g. cuda version, cudnn version, cpu instruction set) to maintain.
=> Add tensorflow with gpu support for windows

hdf5/cppbuild.sh, llvm/cppbuild.sh, mkl-dnn/cppbuild.sh, opencv/cppbuild.sh, tensorflow/cppbuild.sh
Like I mentioned in #568 compilation using multiple cores does not work correctly right now. We are using `/maxcpucount` which builds multiple projects at ones. To compile in parallel we need to tell the compiler (cl.exe) to use multiple cores.
Reference
https://msdn.microsoft.com/en-us/library/bb385193.aspx?f=255&MSPPError=-2147217396
> /maxcpucount: the MSBuild.exe tool can build multiple projects at the same time
> /MP: compiler (cl.exe) option can build multiple compilation units at the same time
=> Multi processor compilation for windows builds

onnx/README.md, onnx/cppbuild.sh, onnx/src/main/java/org/bytedeco/javacpp/onnx.java, onnx/src/main/java/org/bytedeco/javacpp/presets/onnx.java
This builds without error, but it still doesn't return the Traditional ML ops on call ```org.bytedeco.javacpp.onnx.OpSchemaRegistry.get_all_schemas()```.
It returns 115 ops, whereas doing the same thing in python returns 133.
Digging in a bit more, calling `org.bytedeco.javacpp.onnx.RegisterOnnxMLOperatorSetSchema()` 
results in:
`java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.onnx.RegisterOnnxMLOperatorSetSchema()V
at org.bytedeco.javacpp.onnx.RegisterOnnxMLOperatorSetSchema(Native Method)`
Which is strange, since we already link to both of the .so files the ONNX build produces.
I think the root cause is again the rvalue thing, specifically this line in schema.h : ```void RegisterSchema(OpSchema&& schema)```.
Is it possible to apply `std::move` to get the rvalue?
Any ideas?
=> Build with Traditional ML support (ONNX-ML)

mkl-dnn/cppbuild.sh
At least v0.16, MKL-DNN try to enable `-march=native -mtune=native` when `-DARCH_OPT_FLAGS` is not specified ([ref](https://github.com/intel/mkl-dnn/blob/a147082ce98243af386cc7d6498fb6ab11fb98ee/cmake/options.cmake#L53-L71)):
```
set(ARCH_OPT_FLAGS "HostOpts" CACHE STRING
"specifies compiler optimization flags (see below for more information).
If empty default optimization level would be applied which depends on the
compiler being used.
- For Intel(R) C++ Compilers the default option is `-xHOST` which instructs
the compiler to generate the code for the architecture where building is
happening. This option would not allow to run the library on older
architectures.
- For GNU* Compiler Collection version 5 and newer the default options are
`-march=native -mtune=native` which behaves …
```
=> Disable `ARCH_OPT_FLAGS` in mkl-dnn

README.md, opencv/cppbuild.sh
Built on Loongson 3A3000 CPUs, which are little-endian MIPS64.
OS: Loongnix (based on Fedora 21, http://www.loongnix.org)
gcc: 4.9.3
glibc: 2.20
jdk: OpenJDK 8 ported by loongson (http://ftp.loongnix.org/toolchain/java/openjdk8/jdk8-mips64-8.tar.gz)
=> Add support for linux-mips64el to OpenCV

CHANGELOG.md, opencv/src/main/java/org/bytedeco/javacpp/helper/opencv_core.java
AbstractArray.createIndexer doesn't support Mat with more than 2 dimensions.
Added AbstractMat.createIndexer that does.
The channels are considered as an additional dimension in the indexer, but this dimension
can be omitted in a long[] array of indices for mats with only 1 channel.
One limitation : Mat theoretically accepts steps that are not multiple of the element size, but indexer does not. An exception is thrown by createIndexer if this occurs.
In JavaCPP, Indexer.rows, cols, width, heads, channels should also be deprecated or modified to return -1 if the number of dimensions of the indexer is not 3.
=> OpenCV: Added support for nD to AbstractMat

opencv/pom.xml, pom.xml
Currently, the pom uses `<compileSourceRoots>` in the configuration of the default execution of the maven compiler to add the generated sources and the possible java sources included in the library distribution.
This configuration seems to remain local to the compiler and is not used by the javadoc and maven-source plugins.
I suggest to replace this (quite undocumented) config by the use of the `add-source` goal of `build-helper-maven-plugin`.
This is yet another plugin to add to each pom, but it seems cleaner and prevent the reconfiguration of the source paths for javadoc and maven-source.
=> Set compile source roots using build-helper plugin

tesseract/samples/src/main/java/org/bytedeco/javacpp/samples/tesseract/IteratorOverClassifierChoicesExample.java, tesseract/samples/src/main/java/org/bytedeco/javacpp/samples/tesseract/OrientationAndScriptDetectionExample.java, tesseract/samples/src/main/java/org/bytedeco/javacpp/samples/tesseract/ResultIteratorExample.java
As follow up to the previous branch, this ports more API examples to Java
=> More tesseract examples

cuda/pom.xml, mkl/pom.xml, pom.xml
Ensure moditect adds the module-info to the target jar, and not a jar fetched from maven repository.
Also commented out an <include> that seems useless.
=> Replace jar GAV by jar filename in moditect config

CHANGELOG.md, artoolkitplus/platform/pom.xml, chilitags/platform/pom.xml, cpu_features/platform/pom.xml, ffmpeg/platform/pom.xml, fftw/platform/pom.xml, flandmark/platform/pom.xml, gsl/platform/pom.xml, leptonica/platform/pom.xml, openblas/platform/pom.xml, opencv/platform/pom.xml, tensorflow/platform/pom.xml, tesseract/platform/pom.xml
Android expects the native library to be installed in `/lib/<abi>` directory.
That's why in the jars of native libraries the libraries are in `/lib/<abi>` instead of the `/org/bytedeco/<presets>/<system>-<abi>/` path used for other platforms.
So when using JPMS and bringing in the module graph the native jars of multiple presets for android, files in directory `/lib/<abi>` are present in multiple modules, leading to a split package exception.
Note that this only happens :
- when using JPMS (so not on Android since Android doesn't support JPMS yet)
- when bringing the native jars for android and for an abi not containing a `-` into the module graph (problably using some `requires org.bytedeco.<preset>.platform` in the application `module-info.java`). Since directories with a `-` are not …
=> Comment out requires to android native modules

cuda/src/main/java9/module-info.java
The produced cuda jar is now considered valid as a Java 9 module.
I'm not sure if the packages being missing are a symptom of an underlying issue, or if the module file was in error. I also checked a few of the other Jars (any jar that was being used by deeplearning4j to be precise) and they all are accepted into a Java 9+ build.
The command `java -p JAR --describe-module MODULE` can be used to check any produced jars.
**Old**
```
> java -p .\cuda-10.2-7.6-1.5.2.jar --describe-module org.bytedeco.cuda
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: .\cuda-10.2-7.6-1.5.2.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Package org.bytedeco.cuda.npps not found in module
```
**Fixed**
```
> java -p …
```
=> [CUDA] Removed missing Java 9 package exports

CHANGELOG.md, arpack-ng/src/main/java9/module-info.java, gsl/src/main/java9/module-info.java, gym/src/main/java9/module-info.java, mxnet/src/main/java9/module-info.java, scipy/src/main/java9/module-info.java
Result of automatic validation of all non-native module-info using:
```
java -p xxx.jar --describe-module org.bytedeco.xxx
```
(using java 9+)
See [PR 880](https://github.com/bytedeco/javacpp-presets/pull/880)
=> Fix various typo in module-info exports

CHANGELOG.md, llvm/samples/llvm/LLVMEmitObjectAndBitcodeFiles.java, llvm/samples/llvm/LLVMRunFunctionFromBitcode.java
Based on a conversation in the JavaCPP Gitter I have put together two samples showing how to deal with LLVM Bitcode from JavaCPP. The following samples have been added:
- EmitObjectAndBitcodeFiles: A sample explaining how a user may emit both object and LLVM Bitcode files from an in-memory LLVM module. This is a pretty common task when using LLVM so I think it's a good sample to have.
- RunFunctionFromBitcode: A sample parsing an LLVM Bitcode file into an in-memory LLVM module and then running a function inside the module via the LLVM interpreter. This is a continuation of the sample from the Gitter conversation.
=> Add samples showing how to use LLVM modules to produce bitcode files

arpack-ng/pom.xml, caffe/pom.xml, chilitags/pom.xml, cminpack/pom.xml, dnnl/pom.xml, flandmark/pom.xml, gsl/pom.xml, gym/pom.xml, mxnet/pom.xml, ngraph/pom.xml, numpy/pom.xml, nvcodec/pom.xml, onnxruntime/pom.xml, opencv/pom.xml, openpose/pom.xml, pom.xml, pytorch/pom.xml, scipy/pom.xml, tensorflow/pom.xml, tensorrt/pom.xml, tesseract/pom.xml, tvm/pom.xml
Native module currently depends on other native modules with same system, architecture and extension.
For instance `org.bytedeco.opencv.linux.x86_64` descriptor contains `requires org.bytedeco.openblas.linux.x86_64`. But when using a specific extension, like `gpu`, module graph initialization fails when the extension doesn't exist for some dependency, like `openblas` or `javacpp` itself.
This PR removes these dependencies between modules. The preferred way to bring the native modules into the module graph is to rely on Maven dependencies using the `javacpp.platform` and `javacpp.platform.extension` properties, and on `--add-modules ALL-MODULE-PATH` option.
=> Remove JPMS dependencies from native modules

CHANGELOG.md, spinnaker/README.md, spinnaker/samples/Acquisition_C.java, spinnaker/src/gen/java/org/bytedeco/spinnaker/Spinnaker_C/actionCommandResult.java, spinnaker/src/gen/java/org/bytedeco/spinnaker/Spinnaker_C/spinTIFFOption.java, spinnaker/src/gen/java/org/bytedeco/spinnaker/global/Spinnaker_C.java, spinnaker/src/main/java/org/bytedeco/spinnaker/presets/Spinnaker_C.java
After JavaCPP fix #477, `enum` for `spinError` was no longer generated. Add line in `Spinaker_C` preset to force `enum` generation and make sure that it is correctly named in generated Java code.
Large part of the diff is due to `enum`s in generated code no longer having prefix "_"
=> [Spinnaker] Correct Spinnaker_C preset to bring back enum generation for 'spinError'

CHANGELOG.md, cpython/src/main/java/org/bytedeco/cpython/presets/python.java, gym/src/main/java/org/bytedeco/gym/presets/gym.java, llvm/src/main/java/org/bytedeco/llvm/presets/LLVM.java, numpy/src/main/java/org/bytedeco/numpy/presets/numpy.java, opencv/src/main/java/org/bytedeco/opencv/opencv_python3.java, scipy/src/main/java/org/bytedeco/scipy/presets/scipy.java, tensorflow/src/main/java/org/bytedeco/tensorflow/presets/tensorflow.java, tvm/src/main/java/org/bytedeco/tvm/presets/tvm.java
With this PR I suggest to store `pythonFile` computed in the `cpython.presets.python.cachePackage()` in a static variable and to return it if it is already computed to prevent caching of the python packages multiple times.
I assume the result should be the same in each call?
This method is called twice when using the embeddedpython.Python class (in a stripped variant) and each call takes at least one third of the 2 seconds initialization time of `embeddedpython.Python`. So also caching the path would speed up the initialization significantly.
Actually this method could be synchronized to prevent concurrent caching of the packages. If you agree I can update this PR accordingly.
=> Synchronize and prevent repeated package caching in all presets

lz4/cppbuild.sh
On Mac OS the library for LZ4 cannot be loaded:
```
java.lang.UnsatisfiedLinkError: no jnilz4 in java.library.path: [/Users/jenkins/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
at java.base/java.lang.System.loadLibrary(Unknown Source)
at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1762)
at org.bytedeco.javacpp.Loader.load(Loader.java:1369)
at org.bytedeco.javacpp.Loader.load(Loader.java:1181)
at org.bytedeco.javacpp.Loader.load(Loader.java:1157)
at org.bytedeco.lz4.global.lz4.<clinit>(lz4.java:14)
at org.knime.core.columnar.arrow.compress.Lz4BlockCompressionCodec.doDecomp …
```
=> Fix rpath for LZ4 on Mac

.github/workflows/tritonserver.yml, CHANGELOG.md, README.md, platform/pom.xml, tritonserver/README.md, tritonserver/platform/pom.xml, tritonserver/platform/redist/pom.xml, tritonserver/pom.xml, tritonserver/samples/pom.xml, tritonserver/src/main/java/org/bytedeco/tritonserver/presets/tritonserver.java
The old version is no longer available, so this ticket updates the Maven version in the README.
=> Update Maven Version For Triton Server README

ffmpeg/cppbuild.sh
=> issue_1136: explicitly disable libxcb on ffmpeg macos x86 build

ffmpeg/cppbuild.sh, ffmpeg/src/main/java/org/bytedeco/ffmpeg/presets/avutil.java
Repeated the same thing we did on macos with the linux build for ffmpeg.
=> issue_1136 Remove linking with x11 on linux for ffmpeg

mkl-dnn/pom.xml, openblas/pom.xml, pom.xml
I got error when building openblas using mingw on Windows.
Because, when i build on Windows, the maven variable(project.basedir)'s path separator is backslash, so bash can't find the shell file.
=> Change the absolute path to a relative path about postbuild.sh execute in pom.xml

CHANGELOG.md, pytorch/src/main/java/org/bytedeco/pytorch/AbstractTensor.java
Add `shape()` convenience method, similar to `sizes().vec().get()`. See #1068 for discussion.
=> Add `shape()` convenience method

.github/workflows/lz4.yml, CHANGELOG.md, lz4/cppbuild.sh, lz4/platform/pom.xml, pom.xml
This PR enables the build of the macosx-arm64 preset for lz4.
Build is working, please let me know if anything else is missing.
(I created the PR with the wrong account earlier, that is why I closed that one and opened this one)
=> Add macosx-arm64 preset for lz4

bullet/src/gen/java/org/bytedeco/bullet/LinearMath/btIDebugDraw.java, bullet/src/main/java/org/bytedeco/bullet/presets/LinearMath.java
It provides virtual methods that needs to be overriden by a user. Resolves #1249.
=> Virtualize bullet's btIDebugDraw

.github/workflows/tensorflow-lite.yml, CHANGELOG.md, pom.xml, tensorflow-lite/platform/pom.xml
Most of the job was already done.
The build script was already prepared.
This only adds the platform on the pom and the for tensorflow-lite and on the main pom.
And updates the git flow to do the build and release.
=> Add build for tensorflow-lite for platform linux-armhf

CHANGELOG.md, pytorch/src/main/java/org/bytedeco/pytorch/presets/torch.java
I've managed to bundle libcupti by adding it to the link list. Is this the right approach in general?
One issue is that it adds `libcupti.so` without the version information, but `libcuda` links with `libcupti.so.11.8`.
=> Bundle libcupti with libtorch to make it work with cuda-platform-redist

opencv/src/gen/java/org/bytedeco/opencv/global/opencv_calib3d.java, opencv/src/main/java/org/bytedeco/opencv/presets/opencv_calib3d.java
This PR should address #1185 
OpenCV has `cv:::initUndistortRectifyMap` and `cv::fisheye::initUndistortRectifyMap` in the calib3d module. The Java for the fisheye version wasn't getting generated because of the symbol collision. I added a `javaNames` for the fisheye version so it maps to `fisheyeInitUndistortRectifyMap`
=> Address OpenCV fisheye symbol collision

llvm/samples/clang/ClangTokenizeExample.java
Before calling `clang.clang_disposeTokens()`, the previously incremented pointer should be re-set to point back to the beginning of the buffer.
=> Prevent the buffer overflow error in ClangTokenizeExample

CHANGELOG.md, cuda/samples/SampleJpegDecoder.java, cuda/samples/SampleJpegEncoder.java, cuda/src/main/java/org/bytedeco/cuda/presets/nvjpeg.java, nvcodec/src/main/java/org/bytedeco/nvcodec/presets/nvcuvid.java, nvcodec/src/main/java/org/bytedeco/nvcodec/presets/nvencodeapi.java
=> Add jpeg encoder sample and rename author

.github/workflows/cpython.yml, cpython/cppbuild.sh, cpython/platform/pom.xml, pom.xml
I'm not sure if I'm overlooking something, but here's a shot of building cpython for Apple Silicon.
I tried a locally built JAR of this on my MacBook M1 by running the `Sample.java` file and it correctly printed the formatted date.
@saudet what am I missing? Is it really that easy? 😅
=> Build cpython for Mac OSX ARM64

.github/actions/deploy-ubuntu/action.yml, .github/workflows/tritonserver.yml, CHANGELOG.md, tritonserver/README.md, tritonserver/cppbuild.sh
change logic for true/false in cppbuild
=> update true==1 for cppbuild.sh

.github/workflows/depthai.yml, CHANGELOG.md, depthai/README.md, depthai/cppbuild.sh, depthai/platform/pom.xml, depthai/pom.xml, depthai/samples/pom.xml, depthai/src/main/java/org/bytedeco/depthai/presets/depthai.java, pom.xml
=> [DepthAI] Add support for Windows & Android

CHANGELOG.md, platform/pom.xml, pytorch/README.md, pytorch/cppbuild.sh, pytorch/platform/gpu/pom.xml, pytorch/platform/pom.xml, pytorch/pom.xml, pytorch/samples/pom.xml, pytorch/src/gen/java/org/bytedeco/pytorch/cuda/DeviceStats.java, pytorch/src/gen/java/org/bytedeco/pytorch/global/torch.java, pytorch/src/main/java/org/bytedeco/pytorch/presets/torch_cuda.java
Included in this PR:
* Add missing mapping for `std::array<CUDACachingAllocator::Stat>`
* Update to PyTorch 2.1.2
=> [PyTorch] Update to 2.1.2

.github/workflows/pytorch.yml, CHANGELOG.md, pom.xml, pytorch/cppbuild.sh, pytorch/platform/gpu/pom.xml, pytorch/platform/pom.xml, pytorch/pom.xml
Fixes #1461 
Add PyTorch cross-compilation `macosx-x86_64` -> `macosx-arm64`. The idea is to use the host Python interpreter to run `setup.py build` See #1461 for more details about this. Cross-compilation settings are derived from the [PyTorch builder](https://github.com/pytorch/builder/blob/74b04f302afede5c25275d8026f34a06330cc515/wheel/build_wheel.sh#L201-L206).
After some experimentation, I figured out that we can use a Maven profile to to use the host Python interpreter for cross-compilation in CI without affecting the existing native builds.
Since we're building just the C++ part of PyTorch (LibTorch), I think it should be OK to add the host Python interpreter like this. We might need to adapt a little bit once we have CPython and NumPy for arm, if it requires running the host …
=> Add PyTorch macosx-arm64 cross-compiled build

CHANGELOG.md, llvm/README.md, llvm/samples/llvm/EmitBitcode.java, llvm/samples/llvm/Factorial.java, llvm/samples/llvm/MCJIT.java, llvm/samples/llvm/OrcJit.java, llvm/samples/llvm/pom.xml
The LLVM ORC example segfaults when freeing error messages using `LLVMConsumeError` because `LLVMGetErrorMessage` already consumes the error.
- Fixed error handling
- Removed unnecessary initialization / function calls
- Renamed `Factorial` example to `MCJIT` to highlight the difference between `MCJIT` and `ORC`
- Added info that `ORC` is newer than `MCJIT` to the readme
- Improved readability
- Fixed typos
- I tested all changes
=> Fixed segfault in LLVM Orc example

CHANGELOG.md, llvm/samples/clang/ClangMemoryMgmtExample.java, llvm/samples/clang/pom.xml
The sample demonstrates how to avoid memory leaks when traversing the AST and tokenizing ranges.
For more context, see:
- bytedeco/javacpp#767
=> Add `ClangMemoryMgmtExample` demonstrating how to avoid memory leaks

hdf5/cppbuild.sh
Additional platform check handling in `cppbuild.sh` for linux-arm64 machines to account for aarch64 as a possible machine type.
New code for the `"$MACHINE_TYPE" =~ aarch64` case executes same commands for arm64 machine type, but omitting `-m64` flags from g++ and gcc as they are unnecessary and throw errors on aarch64.
=> Enable HDF5 build on aarch64 machine

.github/actions/deploy-ubuntu/action.yml, CHANGELOG.md, ffmpeg/cppbuild.sh
install libdrm-dev and libva-dev before building
I've also changed as many download links as possible to https in ffmpeg/cppbuild.sh
Fixes #1607
=> Fix FFmpeg vaapi support

llvm/src/main/java/org/bytedeco/llvm/presets/LLVM.java, llvm/src/main/java/org/bytedeco/llvm/presets/clang.java, llvm/src/main/java/org/bytedeco/llvm/program/clang.java
Target LLVM 20.1.7. The [previous commit](https://github.com/bytedeco/javacpp-presets/commit/4bfcd53496e3d8674bdf90959c13ecd6d9f89bed), that was supposed to do this, missed the changes I'm proposing here.
=> Target LLVM 20.1.7
