artoolkitplus/ARToolKitPlus-2.3.1.patch

Hey ! 
I found a bug in ARToolKitPlus,  
I posted it on launchpad:
https://bugs.launchpad.net/artoolkitplus/+bug/1498585
The fix could be put in JavaCPP-presets meanwhile.
Jeremy.

Patched bug in ARToolkitPlus

---

tensorflow/src/main/java/org/bytedeco/javacpp/presets/tensorflow.java

add definition for Map<string, AttrValue>

---

caffe/cppbuild.sh

fix location of hdf5 tar, change tar extraction to be more generic

fix hdf5 stuff

---

cppbuild.sh
librealsense/README.md
librealsense/cppbuild.sh
librealsense/librealsense-1.9.6-linux.patch
librealsense/pom.xml
librealsense/src/main/java/org/bytedeco/javacpp/presets/RealSense.java
pom.xml

Hello, 
I created a preset for librealsense and it was not so painful (much easier than libfreenect2...) , even better it works. 
I also created a camera for JavaCV, which will have its own pull request soon.
It is a little bit Hacky for the patch, but it works nicely for the few features I tried:
- get the color image, 
- get the depth image
- get the extrinsics. 
Cheers, 
Jeremy.

New preset for Intel's librealsense version 1.9.6 .

---

hdf5/cppbuild.sh
hdf5/src/main/java/org/bytedeco/javacpp/presets/hdf5.java

Here's the resubmitted pull request. Seems to have closed the old one when I rebaselined.. I don't seem to have the knack of that sorted out yet!

remove hdf5 build for linux-armhf

---

ffmpeg/src/main/java/org/bytedeco/javacpp/presets/avutil.java

Map FFmpeg errno

---

CHANGELOG.md
caffe/cppbuild.sh

I added the Axpy layers to caffe cppbuild.sh

Updated caffe/cppbuild.sh to add Axpy layer to caffe

---

.travis.yml

I added the gpu support for mac to .travis.yml

Updated .travis.yml to add gpu support for mac-osx

---

cppbuild.sh
ffmpeg/cppbuild.sh
ffmpeg/disable_vp8_loop_filter_simple_neon.patch

verified for NVIDIA Jetson TX2

Support building ffmpeg on arm64

---

CHANGELOG.md
openblas/cppbuild.sh

pretty small change.  I don't know if these are a good set of flags to pass to the compiler, but they seem to work..

adding linux-arm64 as a platform in the openblas build.

---

llvm/src/main/resources/org/bytedeco/llvm/include/FullOptimization.h

Sorry, there was a memory leak.

LLVM optimizeModule() memory leak

---

.github/actions/deploy-centos/action.yml
.github/actions/deploy-macosx/action.yml
.github/actions/deploy-ubuntu/action.yml
.github/actions/deploy-windows/action.yml

This patch implements support for Gradle-based presets for the CI workflows

Support Gradle builds for GitHub Actions

---

CHANGELOG.md
ffmpeg/cppbuild.sh
ffmpeg/ffmpeg.patch

This adds DASH (and I think HLS) support for ffmpeg.
Obsoletes #961

feat: add libxml2 to ffmpeg build

---

depthai/cppbuild.sh

Refer to [https://github.com/bytedeco/javacpp-presets/issues/1057](https://github.com/bytedeco/javacpp-presets/issues/1057),
I gave it a shot. OpenCV_ROOT seems not work.
After using OpenCV_DIR, and change the OPENCV_PATH, then the build works

change OPENCV_PATH and replace OpenCV_ROOT with OpenCV_DIR

---

dnnl/README.md
dnnl/samples/CpuCnnInferenceInt8.java
mkl-dnn/README.md
mkl-dnn/samples/SimpleNetInt8.java

supposedly tested with output.
>java -cp %newcp% CpuCnnInferenceInt8
Simple-net-int8 example passed!

issue 1095 fix

---

.github/workflows/depthai.yml
depthai/README.md
depthai/cppbuild.sh
depthai/platform/pom.xml
depthai/pom.xml
depthai/samples/pom.xml
depthai/src/main/java/org/bytedeco/depthai/presets/depthai.java
platform/pom.xml
pom.xml

Currently targets a temporary development branch of DepthAI with Android support.
Afterwards, when Android support is mainlined the changes will be able to be merged

[WIP] Temporary Android branch build

---

depthai/README.md
depthai/cppbuild.sh
depthai/platform/pom.xml
depthai/pom.xml
depthai/samples/pom.xml
depthai/src/gen/java/org/bytedeco/depthai/DeviceInfo.java
depthai/src/gen/java/org/bytedeco/depthai/XLinkGlobalHandler_t.java
depthai/src/gen/java/org/bytedeco/depthai/deviceDesc_t.java
depthai/src/gen/java/org/bytedeco/depthai/global/depthai.java
platform/pom.xml

Added an initialize function in depthai, which enables passing JavaVM pointer to underlying libusb library for Android usecase

DepthAI (Android experimental) - Initialize with JavaVM function

---

ffmpeg/src/gen/java/org/bytedeco/ffmpeg/global/avutil.java
ffmpeg/src/main/java/org/bytedeco/ffmpeg/presets/avutil.java

Added macros.h, rebuilt, and commited all changes.

issue_1134 Missing macros.h in avutil Properties

---

ffmpeg/platform/gpl/pom.xml

I think that's all you have to do? I don't know how to create the gpl version with maven so not sure.

issue_1139 Add the macosx arm64 version to ffmpeg's platform/gpl

---

tritonserver/samples/Simple.java
tritonserver/samples/SimpleCPUOnly.java

Update the tritonserver simple example to replicate the original example's preprocessor flag behavior.

Replicate Triton Simple Preprocessor Flags

---

nvcodec/README.md
nvcodec/samples/simple/SampleEncodeDecode.java

Fix error and Add cleanup code in `SampleEncodeDecode.java` in nvcodec

---

CHANGELOG.md
ffmpeg/cppbuild.sh

Increase MAX_SLICES in h264dec.h to 256 via sedinplace rule

Update ffmpeg cppbuild.sh

---

arrow/cppbuild.sh
ffmpeg/platform/gpl/pom.xml
opencv/src/main/java/org/bytedeco/opencv/opencv_java.java
opencv/src/main/java/org/bytedeco/opencv/opencv_python3.java

fixes https://github.com/bytedeco/javacpp-presets/issues/1450

Fixed zlib url.

---

.github/actions/deploy-ubuntu/action.yml

Update deploy ubuntu script for RISC-V

Update deploy ubuntu script for RISC-V

---

.github/actions/deploy-windows/action.yml

Related to JavaCPP's [PR #813](https://github.com/bytedeco/javacpp/pull/813)

Add Windows ARM64 support for windows deploy action
